import Button from '@/components/Button'
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Pagina Index</h1>
        <Link href={"/Aminah/teste"}>Ir para Aminah</Link>

        <Button cor ="green">Oi</Button>
        <Button cor = "red">Oi</Button>
        <Button cor = "blue">Oi</Button>
      </main>
      
    </>
  )
}
